"""Schemas package - exports all Pydantic schemas."""

from multi_agent_engine.schemas.enums import (
    TaskType,
    TaskStatus,
    AgentStatus,
    Priority,
    TestType,
    TestPriority,
    TestDomain,
    FailureCategory,
    PRIORITY_SCORES,
)
from multi_agent_engine.schemas.agent_outputs import (
    TestStep,
    TestCase,
    TestReference,
    TestIssue,
    ValidatedTestCase,
    ParseStoryOutput,
    ClassifyDomainOutput,
    FetchContextOutput,
    GenerateTestsOutput,
    ValidateTestsOutput,
    AnalyseCoverageOutput,
    TASK_OUTPUT_SCHEMAS,
)
from multi_agent_engine.schemas.tasks import (
    ModelConfig,
    TaskCreateRequest,
    TaskAcceptedResponse,
    TaskStatusResponse,
    AgentStatusResponse,
    AgentListResponse,
    QueueDepthResponse,
    TaskResultPayload,
    TaskQueueEntry,
    HealthResponse,
    ErrorResponse,
)

__all__ = [
    # Enums
    "TaskType",
    "TaskStatus",
    "AgentStatus",
    "Priority",
    "TestType",
    "TestPriority",
    "TestDomain",
    "FailureCategory",
    "PRIORITY_SCORES",
    # Agent outputs
    "TestStep",
    "TestCase",
    "TestReference",
    "TestIssue",
    "ValidatedTestCase",
    "ParseStoryOutput",
    "ClassifyDomainOutput",
    "FetchContextOutput",
    "GenerateTestsOutput",
    "ValidateTestsOutput",
    "AnalyseCoverageOutput",
    "TASK_OUTPUT_SCHEMAS",
    # Tasks
    "ModelConfig",
    "TaskCreateRequest",
    "TaskAcceptedResponse",
    "TaskStatusResponse",
    "AgentStatusResponse",
    "AgentListResponse",
    "QueueDepthResponse",
    "TaskResultPayload",
    "TaskQueueEntry",
    "HealthResponse",
    "ErrorResponse",
]
