"""Agent output schemas - structured outputs per agent type."""

from datetime import datetime
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, Field, field_validator

from multi_agent_engine.schemas.enums import TestType, TestPriority, TestDomain


# -----------------------------------------------------------------------------
# Common/Shared Schemas
# -----------------------------------------------------------------------------


class TestStep(BaseModel):
    """Single step within a test case."""

    step_number: int = Field(..., ge=1, description="Ordered index starting at 1")
    action: str = Field(..., min_length=1, description="Action to perform")
    input_data: Optional[Dict[str, Any]] = Field(
        default=None, description="Test data for this step"
    )
    expected_outcome: str = Field(..., min_length=1, description="Per-step expected result")


class TestCase(BaseModel):
    """Structured test case generated by TestGeneratorAgent."""

    test_id: UUID = Field(..., description="Agent-assigned unique ID")
    title: str = Field(..., min_length=1, max_length=200, description="Descriptive test name")
    type: TestType = Field(..., description="Test type classification")
    preconditions: List[str] = Field(default_factory=list, description="Required setup state")
    steps: List[TestStep] = Field(..., min_length=1, description="Ordered action descriptions")
    expected_result: str = Field(..., min_length=1, description="Observable pass criterion")
    tags: List[str] = Field(default_factory=list, description="Classification labels")
    priority: TestPriority = Field(default=TestPriority.P1, description="Test priority")
    estimated_duration_seconds: int = Field(
        default=60, ge=1, description="Execution time estimate"
    )

    @field_validator("tags")
    @classmethod
    def validate_tags(cls, v: List[str]) -> List[str]:
        """Validate tag length."""
        return [tag[:32] for tag in v[:10]]  # Max 10 tags, 32 chars each


class TestReference(BaseModel):
    """Reference to a historical test case from Memory Layer."""

    test_id: UUID
    title: str
    similarity_score: float = Field(..., ge=0.0, le=1.0)
    source_project_id: Optional[UUID] = None


class TestIssue(BaseModel):
    """Quality issue flagged during validation."""

    test_id: UUID
    issue_type: str = Field(..., description="Type of issue detected")
    severity: str = Field(..., description="LOW, MEDIUM, HIGH")
    description: str = Field(..., description="Issue description")


class ValidatedTestCase(BaseModel):
    """Test case with validation annotations."""

    test_case: TestCase
    is_valid: bool = True
    validation_notes: List[str] = Field(default_factory=list)
    quality_score: float = Field(default=1.0, ge=0.0, le=1.0)


# -----------------------------------------------------------------------------
# Per-Agent Output Schemas
# -----------------------------------------------------------------------------


class ParseStoryOutput(BaseModel):
    """Output schema for PARSE_STORY agent."""

    actors: List[str] = Field(
        default_factory=list, description="Identified roles/personas"
    )
    actions: List[str] = Field(
        default_factory=list, description="Behaviours described in the story"
    )
    acceptance_criteria: List[str] = Field(
        default_factory=list, description="Explicit or inferred acceptance conditions"
    )
    ambiguities: List[str] = Field(
        default_factory=list, description="Unclear or conflicting story elements"
    )


class ClassifyDomainOutput(BaseModel):
    """Output schema for CLASSIFY_DOMAIN agent."""

    domains: List[str] = Field(
        default_factory=list,
        description="Test domains: UI, API, DATABASE, AUTH, PERFORMANCE, SECURITY",
    )
    primary_domain: str = Field(..., description="Highest-confidence domain")
    confidence_scores: Dict[str, float] = Field(
        default_factory=dict, description="Per-domain confidence 0.0-1.0"
    )

    @field_validator("confidence_scores")
    @classmethod
    def validate_scores(cls, v: Dict[str, float]) -> Dict[str, float]:
        """Ensure confidence scores are in valid range."""
        return {k: max(0.0, min(1.0, score)) for k, score in v.items()}


class FetchContextOutput(BaseModel):
    """Output schema for FETCH_CONTEXT agent."""

    relevant_tests: List[TestReference] = Field(
        default_factory=list, description="Top-k similar historical test cases"
    )
    patterns: List[str] = Field(
        default_factory=list, description="Reusable test patterns"
    )
    constraints: List[str] = Field(
        default_factory=list, description="Project-level rules and constraints"
    )
    source_ids: List[UUID] = Field(
        default_factory=list, description="Memory Layer record IDs for traceability"
    )


class GenerateTestsOutput(BaseModel):
    """Output schema for GENERATE_TESTS agent."""

    test_cases: List[TestCase] = Field(
        default_factory=list, description="Generated test cases"
    )
    generation_notes: str = Field(
        default="", description="Agent reasoning summary"
    )
    coverage_claims: List[str] = Field(
        default_factory=list, description="Acceptance criteria the tests claim to cover"
    )

    @field_validator("test_cases")
    @classmethod
    def limit_test_cases(cls, v: List[TestCase]) -> List[TestCase]:
        """Cap test cases at maximum limit."""
        from multi_agent_engine.config import get_settings
        settings = get_settings()
        if len(v) > settings.max_generated_tests:
            return v[:settings.max_generated_tests]
        return v


class ValidateTestsOutput(BaseModel):
    """Output schema for VALIDATE_TESTS agent."""

    validated_tests: List[ValidatedTestCase] = Field(
        default_factory=list, description="Tests with validation status"
    )
    removed_duplicates: List[UUID] = Field(
        default_factory=list, description="Test IDs removed as duplicates"
    )
    flagged_issues: List[TestIssue] = Field(
        default_factory=list, description="Tests with detected quality issues"
    )
    overall_quality_score: float = Field(
        default=1.0, ge=0.0, le=1.0, description="0.0-1.0 quality assessment"
    )


class AnalyseCoverageOutput(BaseModel):
    """Output schema for ANALYSE_COVERAGE agent."""

    coverage_matrix: Dict[str, List[UUID]] = Field(
        default_factory=dict, description="Acceptance criterion -> covering test IDs"
    )
    coverage_percentage: float = Field(
        default=0.0, ge=0.0, le=100.0, description="% of criteria with at least one test"
    )
    uncovered_criteria: List[str] = Field(
        default_factory=list, description="Criteria with zero test coverage"
    )


# Map task types to their output schemas
TASK_OUTPUT_SCHEMAS = {
    "PARSE_STORY": ParseStoryOutput,
    "CLASSIFY_DOMAIN": ClassifyDomainOutput,
    "FETCH_CONTEXT": FetchContextOutput,
    "GENERATE_TESTS": GenerateTestsOutput,
    "VALIDATE_TESTS": ValidateTestsOutput,
    "ANALYSE_COVERAGE": AnalyseCoverageOutput,
}
